Patch to README.md
tc39/proposal-pipeline-operator pull request #240
Opened 2021-10-02 09:34 UTC by FrameMuse

I added indents before |> as I mentioned it in #239
I also changed ? to # in a link, so it will lead to the correct question

2021-10-04 17:52 UTC, tabatkins requested changes
I'm happy to accept this overall; I agree that chaining off a value is usually indented, and it will probably become common practice with pipes as well.

I've marked a number of examples where the current indent is correct and intended, when it's piping off of a method chain. The method-call and the pipeline are both doing the same thing, so they're intended to be at the same indent level. Revert those and I can merge.

2021-10-04 17:52 UTC, tabatkins commented on README.md
> +    |> `$ ${^}`
These lines are purposely indented the same amount as the methods. I expect this might become common indenting practice.

2021-10-04 17:52 UTC, tabatkins commented on README.md
> +    |> `$ ${^}`
same here

2021-10-04 17:52 UTC, tabatkins commented on README.md
> +      |> chalk.dim(^, 'node', args.join(' '));
same here

2021-10-04 17:52 UTC, tabatkins commented on README.md
> +    |> console.log(^);
same here

2021-10-04 17:52 UTC, tabatkins commented on README.md
> +    |> x=> `$ ${x}`
same here

2021-10-04 17:52 UTC, tabatkins commented on README.md
> +    |> `$ ${^}`
same here

2021-10-04 19:45 UTC, js-choi commented
I personally feel neutral about this—but I’m fine with it if @tabatkins is fine with it. 🙂

When you make the changes suggested by Tab, then I’ll merge this in.

2021-10-05 05:32 UTC, FrameMuse commented
I was in doubt if it should be indented too, because it's a different chain, unlike method call. But anyway, I tend to agree that they should be flush.

2021-10-05 20:28 UTC, tabatkins approved these changes

2021-10-05 20:28 UTC, merged